# Generated by Django 4.2.13 on 2024-06-04 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_call_load', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callinfo',
            name='messages',
        ),
    ]
